/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SugerenciasRouteImport } from './routes/sugerencias'
import { Route as ActividadIdRouteImport } from './routes/actividad.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SugerenciasRoute = SugerenciasRouteImport.update({
  id: '/sugerencias',
  path: '/sugerencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadIdRoute = ActividadIdRouteImport.update({
  id: '/actividad/$id',
  path: '/actividad/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sugerencias': typeof SugerenciasRoute
  '/actividad/$id': typeof ActividadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sugerencias': typeof SugerenciasRoute
  '/actividad/$id': typeof ActividadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sugerencias': typeof SugerenciasRoute
  '/actividad/$id': typeof ActividadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/sugerencias' | '/actividad/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/sugerencias' | '/actividad/$id'
  id: '__root__' | '/' | '/admin' | '/sugerencias' | '/actividad/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SugerenciasRoute: typeof SugerenciasRoute
  ActividadIdRoute: typeof ActividadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sugerencias': {
      id: '/sugerencias'
      path: '/sugerencias'
      fullPath: '/sugerencias'
      preLoaderRoute: typeof SugerenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividad/$id': {
      id: '/actividad/$id'
      path: '/actividad/$id'
      fullPath: '/actividad/$id'
      preLoaderRoute: typeof ActividadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SugerenciasRoute: SugerenciasRoute,
  ActividadIdRoute: ActividadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
